### ISSUE TITLE
Unable to Encrypt Request...Try again

### ISSUE THREAD

**Issue by Emmanuelfrimpong** [Flutterwave/flutterwave-flutter#73]
I get this error when i try user Test Card ...I always this error on the snackbar...

"Unable to Encrypt Request...Try again"

**Comment by Emmanuelfrimpong** [comment]
I/SurfaceControl(32428): nativeRelease nativeObject s[531916704576]
I/SurfaceControl(32428): nativeRelease nativeObject e[531916704576]
I/ViewRootImpl@aba05aa[MainActivity](32428): ViewPostIme pointer 0
I/ViewRootImpl@aba05aa[MainActivity](32428): ViewPostIme pointer 1
I/flutter (32428): [1179408211, 1162038111, 1413829460, 1684289124, 892418147, 912404785, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
I/flutter (32428): ===========================================
I/flutter (32428): type 'Null' is not a subtype of type 'int' in type cast
I/flutter (32428): ===========================================
I/flutter (32428): #0      FlutterwaveUtils.tripleDESEncrypt (package:flutterwave/utils/flutterwave_utils.dart:18:7)
I/flutter (32428): #1      CardPaymentManager._prepareRequest (package:flutterwave/core/card_payment_manager/card_payment_manager.dart:66:60)
I/flutter (32428): #2      CardPaymentManager.payWithCard (package:flutterwave/core/card_payment_manager/card_payment_manager.dart:85:31)
I/flutter (32428): #3      _CardPaymentState._makeCardPayment (package:flutterwave/widgets/card_payment/card_payment.dart:230:10)
I/flutter (32428): #4      FlutterwaveViewUtils.showConfirmPaymentModal.<anonymous closure>.<anonymous closure> (package:flutterwave/widgets/flutterwave_view_utils.dart:36:49)
I/flutter (32428): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
I/flutter (32428): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
I/flutter (32428): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
I/flutter (32428): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
I/flutter (32428): #9      BaseTapGestureRecognizer.handlePrimaryPointer (
I/flutter (32428): Flutterwave Error: Unable to encrypt request: type 'Null' is not a subtype of type 'int' in type cast===============================================
I/ViewRootImpl@aba05aa[MainActivity](32428): MSG_WINDOW_FOCUS_CHANGED 0 1
I/SurfaceControl(32428): release : mNativeObject = 531914228544 - Surface(name=Surface(name=9d5184c InputMethod)/@0xe616d38 - animation-leash)/@0xfcff772 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154 
I/SurfaceControl(32428): nativeRelease nativeObject s[531914228544]
I/SurfaceControl(32428): nativeRelease nativeObject e[531914228544]
I/SurfaceControl(32428): release : mNativeObject = 531916703040 - Surface(name=Surface(name=51cc739 NavigationBar0)/@0x3b8cb0 - animation-leash)/@0xd1d47c3 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833

**Comment by odunboye** [comment]
Same error, any solution?

**Comment by priyankjain12** [comment]
@odunboye Still facing the issue in v1.0.1. Is there any plan to fix this?

**Comment by afrimglobal** [comment]
Me too, so annoying

**Comment by FredDominant** [comment]
@priyankjain12, @afrimglobal. This library is no more supported. Please make use of [this](https://pub.dev/packages/flutterwave_standard) instead.
