### ISSUE TITLE
Package not working properly. Getting error while testing.

### ISSUE THREAD

**Issue by m1narulal1** [Flutterwave/flutterwave-flutter#78]
Getting error while testing Please check. Added card details on testing account Error raised.
I/flutter (27559): [1179408211, 1162038111, 1413829460, 1680945763, 1714958904, 895693621, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
I/flutter (27559): #0      FlutterwaveUtils.tripleDESEncrypt (package:flutterwave/utils/flutterwave_utils.dart:15:7)
I/flutter (27559): #1      CardPaymentManager._prepareRequest (package:flutterwave/core/card_payment_manager/card_payment_manager.dart:66:60)
I/flutter (27559): #2      CardPaymentManager.payWithCard (package:flutterwave/core/card_payment_manager/card_payment_manager.dart:85:31)
I/flutter (27559): #3      _CardPaymentState._makeCardPayment (package:flutterwave/widgets/card_payment/card_payment.dart:230:10)
I/flutter (27559): #4      FlutterwaveViewUtils.showConfirmPaymentModal.<anonymous closure>.<anonymous closure> (package:flutterwave/widgets/flutterwave_view_utils.dart:36:49)
I/flutter (27559): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
I/flutter (27559): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
I/flutter (27559): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
I/flutter (27559): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
I/flutter (27559): #9      BaseTapGestureRecognizer.handlePrimaryPointer (
E/flutter (27559): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'ChargeResponse' in type cast
E/flutter (27559): #0      _FlutterwaveUIState._handleBackPress (package:flutterwave/widgets/home/flutterwave_payment.dart:419:53)
E/flutter (27559): #1      _FlutterwaveUIState._launchCardPaymentWidget (package:flutterwave/widgets/home/flutterwave_payment.dart:337:5)
E/flutter (27559): <asynchronous suspension>
E/flutter (27559): 
E/flutter (27559): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<ChargeResponse>'
E/flutter (27559): #0      Flutterwave._launchPaymentScreen (package:flutterwave/core/flutterwave.dart:237:10)
E/flutter (27559): <asynchronous suspension>
E/flutter (27559): #1      Flutterwave.initializeForUiPayments (package:flutterwave/core/flutterwave.dart:231:26)
E/flutter (27559): <asynchronous suspension>
E/flutter (27559): #2      _MyHomePageState._handlePaymentInitialization (package:customer/PaymentTest.dart:189:22)
E/flutter (27559): <asynchronous suspension>
E/flutter (27559):

**Comment by holy-dev** [comment]
this is because of trippledes package
